# Let's prepare!
Notebook for preparing our data.
We'll apply 3 types of transformations to it:
1. Imputing its null values;
2. Standardizing it;
3. Window it into time windows.

The processes will be applied to each file individually.
After done, we can join the results from each file to train our models.

### Imputing null values
Para as variáveis numéricas, realizaremos:
- se inteiramente nula: preencher zero; (TODO: testar usar média do seu tipo de anomalia)
- se parcialmente nula: interpolação linear + bfill + ffill.


Para 'class' realizaremos:
- se inteiramente nula: preencher com o seu tipo de anomalia; (TODO: verificar validade desta suposição)
- se parcialmente nula: bfill + ffill.

In [1]:
# pp.process_events(
#     process_fc=pp.transform_with_imputation, 
#     process_fc_args=tuple(zip(
#         imp_metadata['path'], imp_metadata['type_'], 
#         repeat(imp_input_path), repeat(imp_output_path), 
#         repeat(numeric_means_by_event_type), 
#     )),
#     output_folder=imp_output_path, 
#     use_cached=False,

# )

In [2]:
import sys

sys.path.append("..")  # Allows imports from sibling directories

from constants import utils, config
ex_path = "dataset_converted_v10101_split-20_source-all_class-all_well-all_train/4/WELL-00001_20170316120203.parquet"
ex_event = utils.get_event(config.DIR_PROJECT_DATA / ex_path)
ex_event[0:10]

P-PDG       P-TPT     T-TPT  P-MON-CKP  T-JUS-CKP  \
timestamp                                                                     
2017-03-16 12:02:03  38265830.0  13654450.0  117.1953  6029680.0   68.64587   
2017-03-16 12:02:04  38265830.0  13654520.0  117.1947  6030228.0   68.64333   
2017-03-16 12:02:05  38265830.0  13654580.0  117.1942  6030777.0   68.64080   
2017-03-16 12:02:06  38265830.0  13654650.0  117.1937  6031326.0   68.63827   
2017-03-16 12:02:07  38265830.0  13654710.0  117.1932  6031875.0   68.63573   
2017-03-16 12:02:08  38265830.0  13654780.0  117.1926  6032423.0   68.63321   
2017-03-16 12:02:09  38265830.0  13654840.0  117.1921  6032972.0   68.63068   
2017-03-16 12:02:10  38265830.0  13654900.0  117.1916  6033521.0   68.62814   
2017-03-16 12:02:11  38265830.0  13654970.0  117.1911  6034070.0   68.62561   
2017-03-16 12:02:12  38265830.0  13655030.0  117.1906  6034618.0   68.62308   

                     P-JUS-CKGL  T-JUS-CKGL  QGL  class  
timestamp                                                
2017-03-16 12:02:03   3283309.0         NaN  0.0      4  
2017-03-16 12:02:04   3283309.0         NaN  0.0      4  
2017-03-16 12:02:05   3283308.0         NaN  0.0      4  
2017-03-16 12:02:06   3283308.0         NaN  0.0      4  
2017-03-16 12:02:07   3283308.0         NaN  0.0      4  
2017-03-16 12:02:08   3283307.0         NaN  0.0      4  
2017-03-16 12:02:09   3283307.0         NaN  0.0      4  
2017-03-16 12:02:10   3283307.0         NaN  0.0      4  
2017-03-16 12:02:11   3283306.0         NaN  0.0      4  
2017-03-16 12:02:12   3283306.0         NaN  0.0      4

In [3]:
n = 5
ex_event.resample(f'{n}s').mean()

P-PDG       P-TPT      T-TPT  P-MON-CKP  T-JUS-CKP  \
timestamp                                                                      
2017-03-16 12:02:00  38265830.0  13654485.0  117.19500  6029954.0  68.644600   
2017-03-16 12:02:05  38265830.0  13654712.0  117.19316  6031874.6  68.635738   
2017-03-16 12:02:10  38265830.0  13655032.0  117.19056  6034618.4  68.623076   
2017-03-16 12:02:15  38265830.0  13655356.0  117.18796  6037362.4  68.610420   
2017-03-16 12:02:20  38265830.0  13655678.0  117.18536  6040106.2  68.597762   
...                         ...         ...        ...        ...        ...   
2017-03-16 13:59:40  38265830.0  13901756.0  117.04692  5908803.6  69.137942   
2017-03-16 13:59:45  38265830.0  13900112.0  117.04800  5903815.2  69.133580   
2017-03-16 13:59:50  38265830.0  13898470.0  117.04908  5898826.4  69.129226   
2017-03-16 13:59:55  38265830.0  13896830.0  117.05014  5893837.4  69.124864   
2017-03-16 14:00:00  38265830.0  13895840.0  117.05080  5890844.0  69.122250   

                     P-JUS-CKGL  T-JUS-CKGL  QGL  class  
timestamp                                                
2017-03-16 12:02:00   3283309.0         NaN  0.0    4.0  
2017-03-16 12:02:05   3283307.6         NaN  0.0    4.0  
2017-03-16 12:02:10   3283305.8         NaN  0.0    4.0  
2017-03-16 12:02:15   3283303.8         NaN  0.0    4.0  
2017-03-16 12:02:20   3283301.6         NaN  0.0    4.0  
...                         ...         ...  ...    ...  
2017-03-16 13:59:40   3282013.4         NaN  0.0    4.0  
2017-03-16 13:59:45   3282016.0         NaN  0.0    4.0  
2017-03-16 13:59:50   3282018.4         NaN  0.0    4.0  
2017-03-16 13:59:55   3282021.0         NaN  0.0    4.0  
2017-03-16 14:00:00   3282022.0         NaN  0.0    4.0  

[1417 rows x 9 columns]

In [34]:
#ex_event.shape[0]
ex_event[module_constants.event_num_attribs].columns

Index(['P-PDG', 'P-TPT', 'T-TPT', 'P-MON-CKP', 'T-JUS-CKP', 'P-JUS-CKGL',
       'QGL'],
      dtype='object')

In [17]:
import numpy as np
from constants import module_constants
#np.hstack([ex_event[c] for c in ex_event.columns])




ex_event_stacked_num_attribs = np.hstack([np.array(ex_event[c]).reshape((ex_event.shape[0], 1)) for c in ex_event[module_constants.event_num_attribs].columns])
ex_event_class_attribs = np.array(ex_event[module_constants.event_class_attrib])

ex_event_stacked_num_attribs[0], ex_event_class_attribs[0]

(array([3.826583e+07, 1.365445e+07, 1.171953e+02, 6.029680e+06,
        6.864587e+01, 3.283309e+06, 0.000000e+00]),
 array([4]))

In [14]:

def split_sequences(sequences_input, sequence_output, n_steps):
    """split a multivariate sequence into samples"""
    X, y = list(), list()
    for i in range(len(sequences_input)):
        # find the end of this pattern
        end_ix = i + n_steps

        # check if we are beyond the dataset
        if end_ix > len(sequences_input):
            break
        
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences_input[i:end_ix], sequence_output[end_ix-1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [19]:
n_steps=3
X, y = split_sequences(ex_event_stacked_num_attribs, ex_event_class_attribs, n_steps)
print(X.shape, y.shape)

# summarize the data
for i in range(2):
    print(X[i], y[i])

(7076, 3, 7) (7076, 1)
[[3.826583e+07 1.365445e+07 1.171953e+02 6.029680e+06 6.864587e+01
  3.283309e+06 0.000000e+00]
 [3.826583e+07 1.365452e+07 1.171947e+02 6.030228e+06 6.864333e+01
  3.283309e+06 0.000000e+00]
 [3.826583e+07 1.365458e+07 1.171942e+02 6.030777e+06 6.864080e+01
  3.283308e+06 0.000000e+00]] [4]
[[3.826583e+07 1.365452e+07 1.171947e+02 6.030228e+06 6.864333e+01
  3.283309e+06 0.000000e+00]
 [3.826583e+07 1.365458e+07 1.171942e+02 6.030777e+06 6.864080e+01
  3.283308e+06 0.000000e+00]
 [3.826583e+07 1.365465e+07 1.171937e+02 6.031326e+06 6.863827e+01
  3.283308e+06 0.000000e+00]] [4]


In [24]:
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
in_seq3 = np.array([25, 35, 45, 55, 65, 75, 85, 95, 95])
in_seq4 = np.array([35, 45, 55, 65, 75, 85, 95, 95, 95])
out_seq = np.array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
in_seq3 = in_seq3.reshape((len(in_seq3), 1))
in_seq4 = in_seq4.reshape((len(in_seq4), 1))
#out_seq = out_seq.reshape((len(out_seq), 1))

demo_event = np.hstack((in_seq1, in_seq2, in_seq3, in_seq4))
demo_event, out_seq

(array([[10, 15, 25, 35],
        [20, 25, 35, 45],
        [30, 35, 45, 55],
        [40, 45, 55, 65],
        [50, 55, 65, 75],
        [60, 65, 75, 85],
        [70, 75, 85, 95],
        [80, 85, 95, 95],
        [90, 95, 95, 95]]),
 array([ 25,  45,  65,  85, 105, 125, 145, 165, 185]))

In [23]:
n_steps=3
X, y = split_sequences(demo_event, out_seq, n_steps)
print(X.shape, y.shape)

# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(7, 3, 4) (7,)
[[10 15 25 35]
 [20 25 35 45]
 [30 35 45 55]] 65
[[20 25 35 45]
 [30 35 45 55]
 [40 45 55 65]] 85
[[30 35 45 55]
 [40 45 55 65]
 [50 55 65 75]] 105
[[40 45 55 65]
 [50 55 65 75]
 [60 65 75 85]] 125
[[50 55 65 75]
 [60 65 75 85]
 [70 75 85 95]] 145
[[60 65 75 85]
 [70 75 85 95]
 [80 85 95 95]] 165
[[70 75 85 95]
 [80 85 95 95]
 [90 95 95 95]] 185


In [29]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense

n_features = X.shape[2]

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')



In [30]:
model.fit(X, y, epochs=200, verbose=0)